name: Lint PL HTML Files (Reusable)

'on':
  workflow_call:
    inputs:
      test-mode:
        description: 'Enable test mode (expects certain files to fail for validation)'
        required: false
        type: boolean
        default: false
      expected-failures:
        description: 'Comma-separated list of filenames that should fail (only in test mode)'
        required: false
        type: string
        default: ''

jobs:
  lint-html:
    name: Lint HTML Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Run HTML linter
        env:
          TEST_MODE: ${{ inputs.test-mode }}
          EXPECTED_FAILURES: ${{ inputs.expected-failures }}
        run: python3 lint_html.py
