name: Test Linter

'on':
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    name: Test Linter (with expected failures)
    uses: ./.github/workflows/lint-html.yml
    with:
      test-mode: true
      expected-failures: 'example_invalid.html,example_pl_invalid.html'
